---
apiVersion: v1
kind: Namespace
metadata:
  name: streama
  labels:
    name: streama
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: streama
  name: clone
data:
  clone.yaml: |-
    message: welcome clone
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: streama
  name: gateway
data:
  gateway.yaml: |-
    message: welcome gateway
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: streama
  name: reader
rules:
- apiGroups: [""]
  resources: ["routes","pods","pods/log","pods/status","services","services/proxy","configmaps","endpoints","secrets","serviceaccounts","namespaces","namespaces/status","resourcequotas/status","events","bindings","replicationcontrollers","persistentvolumeclaims"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: streama
  name: reader
roleRef:
  kind: Role
  name: reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: streama
  name: clone
spec:
  selector:
    matchLabels:
      run: clone
  replicas: 2
  template:
    metadata:
      labels:
        run: clone
    spec:
      containers:
      - name: clone
        image: ashraf1abdelrasool/clone:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: streama
  name: clone
  labels:
    run: clone
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  #  type: ClusterIP
#  type: LoadBalancer
  #  type: NodePort
  selector:
    run: clone
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: streama
  name: clone
  labels:
    run: clone
spec:
  to:
    kind: Service
    name: clone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: streama
  name: gateway
spec:
  selector:
    matchLabels:
      run: gateway
  replicas: 1
  template:
    metadata:
      labels:
        run: gateway
    spec:
      containers:
      - name: gateway
        image: ashraf1abdelrasool/gateway:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: streama
  name: gateway
  labels:
    run: gateway
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
#  type: ClusterIP
#  type: LoadBalancer
#  type: NodePort
  selector:
    run: gateway
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: streama
  name: gateway
  labels:
    run: gateway
spec:
  to:
    kind: Service
    name: gateway