---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader
rules:
- apiGroups: [""]
  resources: ["pods","services","configmaps"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader
roleRef:
  kind: Role
  name: reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clone
spec:
  selector:
    matchLabels:
      run: clone
  replicas: 1
  template:
    metadata:
      labels:
        run: clone
    spec:
      containers:
      - name: clone
        image: ashraf1abdelrasool/clone:0.0.2-SNAPSHOT
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: clone
  labels:
    run: clone
spec:
  ports:
  - protocol: TCP
    port: 8080
  selector:
    run: clone
  type: NodePort
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: clone
  labels:
    run: clone
spec:
  to:
    kind: Service
    name: clone